name: Tekken Master Mk1 Bot NodeJS CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: Ubuntu 22.04.2

    steps:
      - name: Checkout repository

        uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v1

        with:
          node-version: "18.x"

      - name: Run Yarn

        run: yarn

    #   - name: Start server

    #     run: yarn start
