name: Tekken Master Mk1 Bot NodeJS CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository

        uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v1

        with:
          node-version: "18.x"

      - name: Run Yarn

        run: yarn

  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Rebuild the bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.ssh_key }}
          script: cd "../home/Tekken_master_MK1_Bot/"
            git fetch && git pull
            yarn
            yarn start
